config/routes.rb
CrmMd::Application.routes.draw do

  root :to => 'activities#index'

  ActiveAdmin.routes(self)

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :activities
  resources :events do
    member do
      get "open_details"
    end
  end

  get "events_for_day", to: "events#events_for_day"
  get "profiles", to: 'users#index', as: :profiles
  get "error", to: 'welcome#index', as: :error
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "search_all", to: "search_results#index"

  match "profile/:id", to: "users#show", as: 'profile'
  match "country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/:id/country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "companies/:id/country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/search", to: "companies#search"
  match "contacts", to: "employees#index"

  resources :companies do
    member do
      get 'show_contacts'
      get 'show_address'
      get 'show_comments'
      get 'sales'
      get 'revisions'
      get 'delete_company' # TODO FIX method, it should be delete
    end

    resources :employees do
      member do
        get 'delete_employee' # TODO FIX method, it should be delete
      end

      resources :comments
    end

    resources :addresses
    resources :comments
    resources :sales

    collection { post :search, to: 'companies#search' }
  end

  resources :employees do
    member do
      get 'profile'
      get 'delete_employee'
      get 'revisions'
      get 'comments'
    end
    resources :comments
  end

  resources :sales
  resources :comments

  get "welcome/index"
  match 'set_locale' => 'welcome#set_locale'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :site
  belongs_to :user
  belongs_to :trackable, polymorphic: true
  attr_accessible :action, :trackable, :user_id, :trackable_id, :trackable_type, as: [:default, :admin]
  before_create :set_site_from_user

  def set_site_from_user
    self.site = user.site
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :result_id, :result_date, :result_time, :events_attributes,
                  :commentable_id, :commentable_type, :user_id, as: [:default, :admin]
  belongs_to :commentable, polymorphic: true
  belongs_to :site
  belongs_to :user

  validates_presence_of :content

  has_many :events, :dependent => :destroy
  accepts_nested_attributes_for :events, allow_destroy: true

  before_create :set_site_from_user

  def set_site_from_user
    self.site = user.site
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @activities = @current_site.activities.order('updated_at desc').includes([:user, :trackable]).page(params[:page]).per_page(10)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_commentable

  load_and_authorize_resource

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(params[:comment])
    @comment.user_id = current_user.id

    if @comment.save
      track_activity @comment

      expire_fragment t(:'activity.index.activities')
      expire_fragment "#{@comment.commentable_type.downcase}_#{@comment.commentable_id}_#{t(:'company.show.comments')}"

      respond_to do |format|
        format.js
      end
    else
      redirect_to :back
    end
  end

  def destroy
    @comment.destroy
    @comments_count = @commentable.comments.count

    respond_to do |format|
      format.js
    end
  end

private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
    authorize! :read, @commentable
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/activities/comment/_create.html.erb
<% if comment %>
  <% if comment.commentable_type == 'Company' %>
    <%= t(:"activity.index.added_comment") %> <%= link_to comment.commentable.name, company_path(comment.commentable) %>
  <% elsif comment.commentable_type == 'Employee' %>
    <%= t(:"activity.index.added_note") %> <%= link_to comment.commentable.full_name, company_employee_path(comment.commentable.company, comment.commentable) %>
  <% end %>
  <div><%= sanitize truncate(comment.content, omision: "...", length: 100) %></div>
  <% comment.events.each do |event| %>
    <% if event %>
      <table class='table table-bordered' style="max-width: 400px;">
        <tbody>
          <% if event.comment.commentable_type == "Company" %>
            <tr>
              <td><%= t(:'activity.index.event_type') %></td>
              <td><%= link_to t(Event::RESULT[event.action_id]), events_path %></td>
            </tr>
            <tr>
              <td><%= t(:'activity.index.company') %></td>
              <td><%= link_to event.comment.commentable.name, event.comment.commentable %></td>
            </tr>
            <% if event.employee.present? %>
            <tr>
              <td><%= t(:'activity.index.talked_with') %></td>
              <td><%= link_to event.employee.full_name, company_employee_path(event.employee.company, event.employee) %></td>
            </tr>
            <% end %>
          <% elsif event.comment.commentable_type == "Employee" %>
            <tr>
              <td><%= t(:'activity.index.event_type') %></td>
              <td><%= link_to t(Event::RESULT[event.action_id]), events_path %></td>
            </tr>
            <tr>
              <td><%= t(:'activity.index.employee') %></td>
              <td><%= link_to event.employee.full_name, company_employee_path(event.employee.company, event.employee) %></td>
            </tr>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tbody>
      </table>
    <% else %>
    added event wich has since been removed
    <% end %>
  <% end %>
<% else %>
  added a comment wich has since been removed
<% end %>