config/routes.rb
CrmMd::Application.routes.draw do

  root :to => 'activities#index'

  ActiveAdmin.routes(self)

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :activities
  resources :events do
    member do
      get "open_details"
    end
  end

  get "events_for_day", to: "events#events_for_day"
  get "profiles", to: 'users#index', as: :profiles
  get "error", to: 'welcome#index', as: :error
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "search_all", to: "search_results#index"

  match "profile/:id", to: "users#show", as: 'profile'
  match "country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/:id/country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "companies/:id/country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/search", to: "companies#search"
  match "contacts", to: "employees#index"

  resources :companies do
    member do
      get 'show_contacts'
      get 'show_address'
      get 'show_comments'
      get 'sales'
      get 'revisions'
      get 'delete_company' # TODO FIX method, it should be delete
    end

    resources :employees do
      member do
        get 'delete_employee' # TODO FIX method, it should be delete
      end

      resources :comments
    end

    resources :addresses
    resources :comments
    resources :sales

    collection { post :search, to: 'companies#search' }
  end

  resources :employees do
    member do
      get 'profile'
      get 'delete_employee'
      get 'revisions'
      get 'comments'
    end
    resources :comments
  end

  resources :sales
  resources :comments

  get "welcome/index"
  match 'set_locale' => 'welcome#set_locale'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_paper_trail :on => [:update]

  attr_accessible :birthday, :client_date, :company_id, :completion, :decision, :email, :facebook, :first_name, :gender_id, :job_title_id,
                  :language_id, :last_name, :mobile, :patronymic, :phone, :simtravel,
                  :skype, :user_id, :title, :marked_to_remove, as: [:default, :admin]

  belongs_to :company
  belongs_to :user
  belongs_to :job_title
  has_many :comments, as: :commentable
  has_many :events
  belongs_to :gender
  belongs_to :language

  validates :first_name, :gender_id, presence: true

  TITLE = { 0 => :"employee.title.mrs",
            1 => :"employee.title.mr",
            2 => :"employee.title.miss" }

  def full_name
    "#{last_name} #{first_name} #{patronymic}".strip
  end

  UNRANSACKABLE_ATTRIBUTES = ["id", "user_id", "language", "gender", "company_id", "job_title_id", "decision", "title", "created_at",
                              "updated_at"]

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

  def self.text_search(query)
    if query.present?
      where("first_name LIKE :q
        or last_name LIKE :q
        or patronymic LIKE :q
        or email LIKE :q
        or simtravel LIKE :q
        or mobile LIKE :q", q: "%#{query}%")
    end
  end

  def to_delete?
    if self.marked_to_remove == true
      return true
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :authenticate_user!

  # it will be loaded by cancan
  before_filter :load_company, only: %w(create)
  load_and_authorize_resource

  # GET /employees
  # GET /employees.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: EmployeesDatatable.new(view_context) }
    end
  end

  # Complete profile
  #
  # GET /employees/1
  # GET /employees/1.json
  def show
    @hide_employees = true
    @commentable = @employee
    @comments = @commentable.comments.order('created_at desc')
    @comment = Comment.new
    @company = @employee.company

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # Popup profile with limited info
  def profile
    respond_to do |format|
      format.js
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @show_label = true
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])
    # TODO lz load company
    @employee.company = @company
    @employee.user = current_user

    respond_to do |format|
      if @employee.save
        expire_fragment "#{t(:"activity.index.activities")}"
        track_activity @employee
        format.html { redirect_to @company, notice: "#{t(:"messages.created")}" }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        expire_fragment "employee_#{@employee.id}_#{t(:"employee.model_title")}_user"
        format.html { redirect_to company_employee_path(@employee.company, @employee), notice: "#{t(:"messages.updated")}" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  def delete_employee
    @employee.update_attributes(marked_to_remove: !@employee.marked_to_remove)

    redirect_to company_employee_path(@employee.company, @employee)
  end

  def comments
    @hide_employees = true
    @commentable = @employee
    @comments = @commentable.comments.order('created_at desc')
    @comment = Comment.new
  end

  def revisions
    @versions = @employee.versions.order("created_at desc")
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def job_title(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end
    # TODO filter by site
    f.collection_select :job_title_id, JobTitle.find(:all), :id, lang, { :include_blank => t(:"employee.form.select_job") }
  end

  def gender(f)
    if current_language == 'ro'
      gender = :name_ro
    elsif current_language == 'ru'
      gender = :name_ru
    else
      gender = :name
    end

    f.collection_select :gender_id, Gender.all, :id, gender, { :include_blank => t(:"employee.form.select_gender") }, class: "select required"
  end

  def language(f)
    if current_language == 'ro'
      language = :name_ro
    elsif current_language == 'ru'
      language = :name_ru
    else
      language = :name
    end
    # TODO filter by site
    f.collection_select :language_id, Language.all, :id, language, { :include_blank => t(:"employee.form.select_language") }
  end

  def dt_job_title(employee)
    if employee.job_title.present?
      if current_language == 'ro'
        employee.job_title.name_ro
      elsif current_language == 'ru'
        employee.job_title.name_ru
      else
        employee.job_title.name
      end
    end
  end

  def dt_language(employee)
    if employee.language.present?
      if current_language == 'ro'
        employee.language.name_ro
      elsif current_language == 'ru'
        employee.language.name_ru
      else
        employee.language.name
      end
    end
  end

  def dt_gender(employee)
    if current_language == 'ro'
      employee.gender.name_ro
    elsif current_language == 'ru'
      employee.gender.name_ru
    else
      employee.gender.name
    end
  end

  def name_it_e(f, key)
    if f == 'title'
      if key.present?
        result = I18n.t Employee::TITLE[key]
      else
        result = '__'
      end
    elsif f == 'gender_id'
      result = Gender.find key
      result_name_e(result)
    elsif f == 'company_id'
      result = Company.find(key).name
    elsif f == 'language_id'
      if key.present?
        result = Language.find key
        result_name_e(result)
      else
        return '__'
      end
    elsif f == 'job_title_id'
      result = JobTitle.find key
      result_name_e(result)
    elsif f == 'decision'
      decision(key)
    elsif f == 'marked_to_remove'
      marked_to_remove_e(key)
    else f == 'client_at'
      return key
    end
  end

  def result_name_e(result)
    if current_language == 'en'
      return result.name
    elsif current_language == 'ro'
      return result.name_ro
    else
      return result.name_ru
    end
  end

  def decision(key)
    t(key ? :to_delete : :to_not_delete)
  end

  def marked_to_remove_e(key)
    decision(key)
  end
end

app/views/employees/_comments.html.erb
<h4><%= t(:"comments.form.add_comments") %></h4>
<div class="img-polaroid"><%= render partial: 'comments/form' %></div>

<div class="page-header"><h4><%= t(:"comments.form.comments") %> <span id="comments_count"><%= @comments.count %></span></h4></div>
<div class="comments">
  <%= render @comments %>
</div>

app/views/employees/_employee_profile.html.erb
  <div class="span8">
    <%= render 'profile_for_user' %>
  </div>
<%= link_to t(:'employee.form.full_profile'), company_employee_path(@employee.company, @employee) %>

app/views/employees/_field_filter.html.erb
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <%= t(:"employee.index.filter") %>
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="well well-small">
          <ul class="filter">
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(0);" checked><%= t(:"employee.index.id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(1);" checked><%= t(:"employee.index.full_name") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(2);" checked><%= t(:"employee.index.gender") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(3);" checked><%= t(:"employee.index.language") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(4);" checked><%= t(:"employee.index.company_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(5);" checked><%= t(:"employee.index.job_title_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(6);" checked><%= t(:"employee.index.phone") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(7);" checked><%= t(:"employee.index.mobile") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(8);" checked><%= t(:"employee.index.simtravel") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(9);" checked><%= t(:"employee.index.email") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(10);" checked><%= t(:"employee.index.skype") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(11);" checked><%= t(:"employee.index.facebook") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/_history.html.erb
<h4><%= t(:'changes_history') %></h4>
<div class="accordion" id="accordion2">
  <% @versions.each_with_index do |version, index| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <div class="index pull-left"><%= index + 1 %></div>
      <div class="version_date">
      <%= link_to "#collapse#{index+1}", class: "accordion-toggle", data: {toggle: "collapse", parent: "#accordion2"} do %>
        <%= User.find(version.whodunnit).full_name %> <%= t(:'changed_at') %> <%= l version.created_at, format: :long %>
      <% end %>
      </div>
    </div>
    <div id="collapse<%= index+1 %>" class="accordion-body collapse">
      <div class="accordion-inner">
        <div>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th></th>
                <th><%= t(:"company.history.from") %></th>
                <th><%= t(:"company.history.to") %></th>
              </tr>
            </thead>
            <tbody>
              <% version.changeset.each do |set| %>
                <tr>
                  <td><%= t(:"employee.index.#{set[0]}") %></td>
                  <td><%= name_it_e(set[0], set[1][0]) %></td>
                  <td><%= name_it_e(set[0], set[1][1]) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to t(:"history.restore"), revert_version_path(version), :method => :post %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/employees/_marked_to_delete.html.erb
<div class="alert alert-error">
  <%= t(:"marked_to_delete") %>
</div>
<% if can? :manage, @all %>
<%= link_to t(:"helpers.links.cancel"), delete_employee_company_employee_path(@company, @employee), :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
<% end %>

app/views/employees/_profile_for_owner.html.erb
    <dl class="dl-horizontal">
      <dt><strong><%= I18n.t(:"employee.form.user_id") %>:</strong></dt>
      <dd><%= link_to @employee.user.full_name, profile_path(@employee.user) %></dd>
      <dt><strong><%= I18n.t(:"employee.form.created_at") %>:</strong></dt>
      <dd><%= l @employee.created_at, format: :long %></dd>
      <dt><strong><%= I18n.t(:"employee.form.title") %>:</strong></dt>
      <dd><%= best_in_place @employee, :title, :type => :select, :collection => Employee::TITLE.map{|key, value| [key, t(value)]} %></dd>
      <dt><strong><%= I18n.t(:"employee.form.last_name") %>:</strong></dt>
      <dd><%= best_in_place @employee, :last_name, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.first_name") %>:</strong></dt>
      <dd><%= best_in_place @employee, :first_name, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.patronymic") %>:</strong></dt>
      <dd><%= best_in_place @employee, :patronymic, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.gender") %>:</strong></dt>
      <dd>
        <% if current_language == "ro" %>
          <%= best_in_place @employee, :gender_id, :type => :select, :collection => Gender.all.map{|x| [x.id, x.name_ro]} %>
        <% elsif current_language == "en" %>
          <%= best_in_place @employee, :gender_id, :type => :select, :collection => Gender.all.map{|x| [x.id, x.name]} %>
        <% else %>
          <%= best_in_place @employee, :gender_id, :type => :select, :collection => Gender.all.map{|x| [x.id, x.name_ru]} %>
        <% end %>
      </dd>
      <dt><strong><%= I18n.t(:"employee.form.birthday") %>:</strong></dt>
      <dd><%= @employee.birthday.present? ? l(@employee.birthday, format: :long) : "" %></dd>
      <dt><strong><%= I18n.t(:"employee.form.language") %>:</strong></dt>
      <dd>
        <%#= Employee::LANGUAGE[@employee.language] %>
        <% if current_language == "ro" %>
          <%= best_in_place @employee, :language_id, :type => :select, :collection => Language.all.map{|x| [x.id, x.name_ro]} %>
        <% elsif current_language == "en" %>
          <%= best_in_place @employee, :language_id, :type => :select, :collection => Language.all.map{|x| [x.id, x.name]} %>
        <% else %>
          <%= best_in_place @employee, :language_id, :type => :select, :collection => Language.all.map{|x| [x.id, x.name_ru]} %>
        <% end %>
      <dt><strong><%= I18n.t(:"employee.form.company_id") %>:</strong></dt>
      <dd>
        <%= best_in_place @employee, :company_id, type: :select, collection: Company.all.map{|x| [x.id, x.name]} %>
      </dd>
      <dt><strong><%= I18n.t(:"employee.form.job_title_id") %>:</strong></dt>
      <dd>
        <% if current_language == "ro" %>
          <%= best_in_place @employee, :job_title_id, :type => :select, :collection => JobTitle.all.map{|x| [x.id, x.name_ro]} %>
        <% elsif current_language == "en" %>
          <%= best_in_place @employee, :job_title_id, :type => :select, :collection => JobTitle.all.map{|x| [x.id, x.name]} %>
        <% else %>
          <%= best_in_place @employee, :job_title_id, :type => :select, :collection => JobTitle.all.map{|x| [x.id, x.name_ru]} %>
        <% end %>
      </dd>
      <dt><strong><%= I18n.t(:"employee.form.decision") %>:</strong></dt>
      <dd>
        <%= best_in_place @employee, :decision, :type => :checkbox,
                            :collection => [I18n.t(:"employee.form.cant_take_decision"), I18n.t(:"employee.form.take_decision")] %>
      </dd>
      <dt><strong><%= I18n.t(:"employee.form.phone") %>:</strong></dt>
      <dd><%= best_in_place @employee, :phone, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.mobile") %>:</strong></dt>
      <dd><%= best_in_place @employee, :mobile, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.simtravel") %>:</strong></dt>
      <dd><%= best_in_place @employee, :simtravel, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.email") %>:</strong></dt>
      <dd><%= best_in_place @employee, :email, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.skype") %>:</strong></dt>
      <dd><%= best_in_place @employee, :skype, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.facebook") %>:</strong></dt>
      <dd><%= best_in_place @employee, :facebook, opts %></dd>
      <dt><strong><%= I18n.t(:"employee.form.client_date") %>:</strong></dt>
      <dd><%= @employee.client_date? ? l(@employee.client_date, format: :long) : '' %></dd>
<!--       <dt><strong><%#= I18n.t(:"employee.form.completion") %>:</strong></dt>
      <dd><%#= best_in_place @employee, :completion %></dd> -->
    </dl>

app/views/employees/_profile_for_user.html.erb
    <dl class="dl-horizontal">
<!--       <dt><strong><%#= I18n.t(:"employee.form.title") %>:</strong></dt>
      <dd><%#= best_in_place @employee, :title, :type => :select, :collection => Employee::TITLE.map{|key, value| [key, t(value)]} %></dd> -->
      <dt><strong><%= I18n.t(:"employee.form.birthday") %>:</strong></dt>
      <dd><%= @employee.birthday? ? l(@employee.birthday, format: :long) : "" %></dd>
      <dt><strong><%= I18n.t(:"employee.form.language") %>:</strong></dt>
      <dd><%= dt_language(@employee) %></dd>
      <dt><strong><%= I18n.t(:"employee.form.company_id") %>:</strong></dt>
      <dd><%= link_to @employee.company.name, company_path(@employee.company) %></dd>
      <dt><strong><%= I18n.t(:"employee.form.job_title_id") %>:</strong></dt>
      <dd><%= dt_job_title(@employee) %></dd>
      <dt><strong><%= I18n.t(:"employee.form.decision") %>:</strong></dt>
      <dd><%= @employee.decision? ? t(:"employee.form.take_decision") : t(:"employee.form.cant_take_decision") %></dd>
      <dt><strong><%= I18n.t(:"employee.form.phone") %>:</strong></dt>
      <dd><%= @employee.phone %></dd>
      <dt><strong><%= I18n.t(:"employee.form.mobile") %>:</strong></dt>
      <dd><%= @employee.mobile %></dd>
      <dt><strong><%= I18n.t(:"employee.form.simtravel") %>:</strong></dt>
      <dd><%= @employee.simtravel %></dd>
      <dt><strong><%= I18n.t(:"employee.form.email") %>:</strong></dt>
      <dd><%= @employee.email %></dd>
      <dt><strong><%= I18n.t(:"employee.form.skype") %>:</strong></dt>
      <dd><%= @employee.skype %></dd>
      <dt><strong><%= I18n.t(:"employee.form.facebook") %>:</strong></dt>
      <dd><%= @employee.facebook %></dd>
      <dt><strong><%= I18n.t(:"employee.form.client_date") %>:</strong></dt>
      <dd><%= @employee.client_date? ? l(@employee.client_date, format: :long) : "" %></dd>
      <hr>
      <dt><strong><%= I18n.t(:"employee.form.user_id") %>:</strong></dt>
      <dd><%= link_to @employee.user.full_name, profile_path(@employee.user) %></dd>
      <dt><strong><%= I18n.t(:"employee.form.created_at") %>:</strong></dt>
      <dd><%= l @employee.created_at, format: :long %></dd>
    </dl>

app/views/employees/comments.js.erb
$('li.active').removeClass('active');
$('li.comments_tab').addClass('active');
$('.right_side').html("<%= j render(partial: 'comments') %>");
$('.total_comments').html("<%= @employee.comments.count %>");

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<div class="page-header">
  <h2><%= t(:"employee.index.contacts") %></h2>
</div>
<%= render 'field_filter' %>
<hr>
<table id="employees" class="display" data-source="<%= employees_url(format: "json") %>" data-language="<%= current_language %>">
  <thead>
    <tr>
      <th><%= t(:"employee.index.id") %></th>
      <th><%= t(:"employee.index.full_name") %></th>
      <th><%= t(:"employee.index.gender") %></th>
      <th><%= t(:"employee.index.language") %></th>
      <th><%= t(:"employee.index.company_id") %></th>
      <th><%= t(:"employee.index.job_title_id") %></th>
      <th><%= t(:"employee.index.phone") %></th>
      <th><%= t(:"employee.index.mobile") %></th>
      <th><%= t(:"employee.index.simtravel") %></th>
      <th><%= t(:"employee.index.email") %></th>
      <th><%= t(:"employee.index.skype") %></th>
      <th><%= t(:"employee.index.facebook") %></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
<%#= link_to t('.new', :default => t("helpers.links.new")), new_employee_path, :class => 'btn btn-primary' %>
<div id="modal-window" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel" class="modal_title">Loading...</h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h3><%= t(:"employee.form.add_employee_to_company") %> <%= @company.name %> </h3>
</div>
<%= render :partial => 'form' %>

app/views/employees/profile.js.erb
$('.modal-body').html('<%= escape_javascript(render :partial => "employee_profile", :object => @employee) %>');
$('.modal_title').html('<h4><%= @employee.full_name %></h4>');

app/views/employees/revisions.js.erb
$('li.active').removeClass('active');
$('li.history_tab').addClass('active');
$('.right_side').html("<%= j render('history') %>");
$('.total_versions').html("<%= @employee.versions.count %>");

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<%- opts = { :type => :textarea, :ok_button => t(:'save'), :cancel_button => t(:'cancel'), :use_confirm => false, :nil => "" } %>
<%- opts.delete(:ok_button) if params[:suppress_ok_button] %>
<div class="row-fluid">
    <h1><%#= t(:"employee.model_title") %>
      <% if @employee.user == current_user %>
        <%= best_in_place @employee, :first_name, opts %> <%= best_in_place @employee, :last_name, opts %> <%= best_in_place @employee, :patronymic, opts %>
      <% else %>
        <%= @employee.first_name %> <%= @employee.last_name %> <%= @employee.patronymic %>
      <% end %>
    </h1>

<div class="row-fluid">
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                company_path(@company), :class => 'btn'  %>
    <% if can? :update, @employee %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_company_employee_path(@company, @employee), :class => 'btn' %>
      <% if params[:company_id].present? %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                delete_employee_company_employee_path(@company, @employee),
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' unless @employee.to_delete? %>
      <% else %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                delete_employee_employee_path(@employee),
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' unless @employee.to_delete? %>
      <% end %>
    <% end %>
    <span class="marked_to_delete pull-right">
      <% if @employee.to_delete? %>
        <%= render 'marked_to_delete' %>
      <% end %>
    </span>
  </div>
</div>

  <div class="span4" style=<%= @employee.to_delete? ? "background:#f2dede;" : "" %>>
  <% if @employee.user == current_user %>
    <%= render 'profile_for_owner', opts: opts %>
  <% else %>
    <% cache "employee_#{@employee.id}_#{t(:"employee.model_title")}_user" do %>
      <%= render 'profile_for_user' %>
    <% end %>
  <% end %>
  </div>

  <div class="span6">
    <ul class="nav nav-tabs">
      <li class="comments_tab active">
        <%= link_to comments_employee_path(@employee), remote: true, class: 'tab_comments' do %>
          <%= t(:"employee.show.comments") %> <span class="badge badge-inverse total_comments"><%= @employee.comments.count %></span></li>
        <% end %>
      </li>
      <% if can? :manage, Version %>
      <li class="history_tab">
        <%= link_to revisions_employee_path, remote: true do %>
        <%= t(:'changes_history') %> <span class="badge badge-inverse total_versions"><%= @employee.versions.count %></span>
        <% end %>
      </li>
      <% end %>
    </ul>

  <div class="right_side">
    <% cache "employee_#{@employee.id}_#{t(:"company.show.comments")}" do %>
      <%= render partial: 'comments' %>
    <% end %>
  </div>
</div>