config/routes.rb
CrmMd::Application.routes.draw do

  root :to => 'activities#index'

  ActiveAdmin.routes(self)

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :activities
  resources :events do
    member do
      get "open_details"
    end
  end

  get "events_for_day", to: "events#events_for_day"
  get "profiles", to: 'users#index', as: :profiles
  get "error", to: 'welcome#index', as: :error
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "search_all", to: "search_results#index"

  match "profile/:id", to: "users#show", as: 'profile'
  match "country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/:id/country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "companies/:id/country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/search", to: "companies#search"
  match "contacts", to: "employees#index"

  resources :companies do
    member do
      get 'show_contacts'
      get 'show_address'
      get 'show_comments'
      get 'sales'
      get 'revisions'
      get 'delete_company' # TODO FIX method, it should be delete
    end

    resources :employees do
      member do
        get 'delete_employee' # TODO FIX method, it should be delete
      end

      resources :comments
    end

    resources :addresses
    resources :comments
    resources :sales

    collection { post :search, to: 'companies#search' }
  end

  resources :employees do
    member do
      get 'profile'
      get 'delete_employee'
      get 'revisions'
      get 'comments'
    end
    resources :comments
  end

  resources :sales
  resources :comments

  get "welcome/index"
  match 'set_locale' => 'welcome#set_locale'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :result_id, :result_date, :result_time, :events_attributes,
                  :commentable_id, :commentable_type, :user_id, as: [:default, :admin]
  belongs_to :commentable, polymorphic: true
  belongs_to :site
  belongs_to :user

  validates_presence_of :content

  has_many :events, :dependent => :destroy
  accepts_nested_attributes_for :events, allow_destroy: true

  before_create :set_site_from_user

  def set_site_from_user
    self.site = user.site
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_commentable

  load_and_authorize_resource

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(params[:comment])
    @comment.user_id = current_user.id

    if @comment.save
      track_activity @comment

      expire_fragment t(:'activity.index.activities')
      expire_fragment "#{@comment.commentable_type.downcase}_#{@comment.commentable_id}_#{t(:'company.show.comments')}"

      respond_to do |format|
        format.js
      end
    else
      redirect_to :back
    end
  end

  def destroy
    @comment.destroy
    @comments_count = @commentable.comments.count

    respond_to do |format|
      format.js
    end
  end

private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
    authorize! :read, @commentable
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment_<%= comment.id %>">
  <div style="border-left: 1px solid rgba(0, 0, 0, 0.2);padding-left:5px;">
    <%= raw comment.content %>
    <div>
      <%= link_to comment.user.full_name, profile_path(comment.user) %> | <%= l comment.created_at, format: :long %>
      <% if can? :destroy, comment %>
      | <%= link_to t(:"helpers.links.destroy"), comment_path(comment), method: :delete, data: { confirm: 'Delete comment?' }, remote: true %>
      <% end %>
    </div>
    <% if comment.events.present? %>
      <table class="table table-condensed">
        <caption><h6>Events</h6></caption>
        <thead>
          <tr>
            <th>Nr.</th>
            <th>Event</th>
            <th>Contact person</th>
            <th>Email/Phone</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          <% comment.events.each_with_index do |event, index| %>
          <tr>
            <td>
              <span class="badge badge-info"><%= index + 1 %></span>
            </td>
            <td>
              <% if event.action_id %>
                <%= t(Event::RESULT[event.action_id]) %>
              <% end %>
            </td>
            <td>
              <%= link_to event.employee.full_name, company_employee_path(event.employee.company, event.employee) if event.employee.present? %>
            </td>
            <td>
              <% unless event.email == "" %>
                <%= event.email %>
              <% end %>
            </td>
            <td>
              <% if event.event_date %>
                <%= l event.event_date, format: :long %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<hr>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment], remote: true do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%#= f.text_area :content, rows: 4, class: "input-xxlarge", placeholder: t(:"comments.form.comment"), required: true %>
    <%= f.text_area :content, :class => "tinymce", :rows => 5, :cols => 120 %>
    <%= tinymce %>
    <div class="errors"></div>
  </div>
  <h5><%= t(:"events.events") %> | <a href="#" class="add"><%= t(:"events.add_event") %></a></h5>
  <div class="items">
    <%= f.nested_fields_for :events do |f| %>
      <fieldset class="span6 item">
        <%= f.select :action_id, Event::RESULT.invert.map{|a, b| [t(a), b] }, {:include_blank => t(:"events.result.result")}, {class: "first_select", required: true} %>
        <%= f.hidden_field :email, placeholder: "Emails", class: "email_field" %>
        <% if @hide_employees %>
          <%= f.hidden_field :employee_id, value: @employee.id %>
        <% else %>
          <% if @company.employee.exists? %>
            <%= f.collection_select :employee_id, @company.employee.find(:all), :id, :full_name, {:prompt => t(:"employee.form.full_name")}, { class: 'contact_field', style: "display: none;" } %>
          <% else %>
            <%= f.collection_select :employee_id, [], [], [], {:prompt => t(:"employee.form.no_contacts")}, { class: 'contact_field', style: "display: none;" } %>
          <% end %>
        <% end %>
        <%= f.hidden_field :event_date, placeholder: t(:"events.date_hour"), class: "datetimepicker date_field" %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <script type="text/javascript">
          var options_ro;
          var options_en;
          var options_ru;

            options_en = {
              timeFormat: 'HH:mm:ss',
              dateFormat: "yy-mm-dd",
            };

            options_ro = {
              timeFormat: 'HH:mm:ss',
              closeText: "Închide",
              prevText: "<Prec",
              nextText: "Următ>",
              currentText: "Azi",
              monthNames: ["Ianuarie", "Februarie", "Martie", "Aprilie", "Mai", "Iunie", "Iulie", "August", "Septebrie", "Octombrie", "Noiembrie", "Decembrie"],
              monthNamesShort: ["Ian", "Feb", "Mar", "Apr", "Mai", "Iun", "Iul", "Aug", "Sept", "Oct", "Noi", "Dec"],
              dayNames: ["duminică", "luni", "marți", "miercuri", "joi", "vineri", "sâmbătă"],
              dayNamesShort: ["dum", "luni", "mar", "mier", "joi", "vin", "sâmb"],
              dayNamesMin: ["Du", "Lu", "Ma", "Mi", "Jo", "Vi", "Sâ"],
              weekHeader: "Săpt",
              dateFormat: "yy-mm-dd",
              firstDay: 1,
              isRTL: false,
              showMonthAfterYear: false,
              yearSuffix: "",
              timeOnlyTitle: 'Alegeți timpul',
              timeText: 'Timpul',
              hourText: 'Ora',
              minuteText: 'Minute',
              secondText: 'Secunde',
              currentText: 'Acum',
              closeText: 'Închide'
            };

            options_ru = {
              timeFormat: 'HH:mm:ss',
              closeText: "Закрыть",
              prevText: "<Пред",
              nextText: "След>",
              currentText: "Сегодня",
              monthNames: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
              monthNamesShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
              dayNames: ["воскресенье", "понедельник", "вторник", "среда", "четверг", "пятница", "суббота"],
              dayNamesShort: ["вск", "пнд", "втр", "срд", "чтв", "птн", "сбт"],
              dayNamesMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
              weekHeader: "Не",
              dateFormat: "yy-mm-dd",
              firstDay: 1,
              isRTL: false,
              showMonthAfterYear: false,
              yearSuffix: "",
              timeOnlyTitle: 'Выберите время',
              timeText: 'Время',
              hourText: 'Часы',
              minuteText: 'Минуты',
              secondText: 'Секунды',
              currentText: 'Теперь',
              closeText: 'Закрыть'
            };

            $('.first_select').change(function(){
              selectBoxValue($(this));
            });

          $('.datetimepicker').datetimepicker(
              <% if current_language == "ro" %>
              options_ro
              <% elsif current_language == "en" %>
              options_en
              <% else %>
              options_ru
              <% end %>
            );
        </script>
        <br>
        <a href="#" class="remove"><%= t(:"events.remove") %></a>
        <hr>
        <%= f.hidden_field :id %>
        <%= f.hidden_field :_destroy %>
      </fieldset>
      <div style="clear:both;"></div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit t(:"comments.form.add_comments") %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function(e) {
  $('FORM').nestedFields();
});
</script>

app/views/comments/_new.html.erb
<h4>Comments</h4>
<%= render 'form' %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  /* Replace the count of comments */
  $('#comments_count, .total_comments').html('<%= @commentable.comments.count %>');
  $(".comments").prepend('<%= j(render(@comment)) %>');
  /* Reset the comment form */
  $(".new_comment")[0].reset();
<% else %>
  alert('Something Went Wrong');
<% end %>

app/views/comments/destroy.js.erb
$(".comments .comment_<%= @comment.id %>").fadeOut();
$('#comments_count, .total_comments').html('<%= @comments_count %>');

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>