config/routes.rb
CrmMd::Application.routes.draw do

  root :to => 'activities#index'

  ActiveAdmin.routes(self)

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :activities
  resources :events do
    member do
      get "open_details"
    end
  end

  get "events_for_day", to: "events#events_for_day"
  get "profiles", to: 'users#index', as: :profiles
  get "error", to: 'welcome#index', as: :error
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "search_all", to: "search_results#index"

  match "profile/:id", to: "users#show", as: 'profile'
  match "country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/:id/country_select_legal", to: "companies#country_select_legal", as: "country_select_legal"
  match "companies/:id/country_select_invoicing", to: "companies#country_select_invoicing", as: "country_select_invoicing"
  match "companies/search", to: "companies#search"
  match "contacts", to: "employees#index"

  resources :companies do
    member do
      get 'show_contacts'
      get 'show_address'
      get 'show_comments'
      get 'sales'
      get 'revisions'
      get 'delete_company' # TODO FIX method, it should be delete
    end

    resources :employees do
      member do
        get 'delete_employee' # TODO FIX method, it should be delete
      end

      resources :comments
    end

    resources :addresses
    resources :comments
    resources :sales

    collection { post :search, to: 'companies#search' }
  end

  resources :employees do
    member do
      get 'profile'
      get 'delete_employee'
      get 'revisions'
      get 'comments'
    end
    resources :comments
  end

  resources :sales
  resources :comments

  get "welcome/index"
  match 'set_locale' => 'welcome#set_locale'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_paper_trail :on => [:update]

  attr_accessible :bank_req, :company_branch_id, :client_at, :client_category_id, :client_type_id, :client_status_id, :marked_to_remove,
                  :email, :facebook, :fax, :fisc_id, :name, :phone, :responsible_id, :skype, :company_source_id,
                  :user_id, :website, :number_employees, :organizational_form_id, :addresses_attributes, as: [:default, :admin]
  validates :name, :company_branch_id, :client_category_id, :client_type_id, :client_status_id,
            :company_source_id, :phone, presence: true

  belongs_to :site
  belongs_to :user
  belongs_to :resp_user, foreign_key: :responsible_id, class_name: 'User'
  belongs_to :company_branch
  belongs_to :company_source
  belongs_to :client_category
  belongs_to :client_type
  belongs_to :client_status
  belongs_to :organizational_form
  has_many :addresses, :dependent => :destroy, :inverse_of => :company
  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :sales, as: :saleable

  accepts_nested_attributes_for :addresses, :allow_destroy => true

  has_many :employee, :dependent => :destroy

  UNRANSACKABLE_ATTRIBUTES = %w(id user_id responsible_id company_branch_id company_source_id client_category_id
    client_type_id client_at client_status_id organizational_form_id created_at)

  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

  def self.text_search(query)
    if query.present?
      where("name LIKE :q
            or email LIKE :q
            or skype LIKE :q
            or bank_req LIKE :q
            or phone LIKE :q
            or website LIKE :q", q: "%#{query}%")
    end
  end

  def to_delete?
    if self.marked_to_remove == true
      return true
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_company, except: %w{index new create search country_select_legal country_select_invoicing}

  load_and_authorize_resource

  # GET /companies
  # GET /companies.json
  def index
    search

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: CompaniesDatatable.new(view_context, @companies) }
    end
  end

  def search
    @search = @current_site.companies.search(params[:q])
    @companies = @search.result
    @search.build_condition
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @commentable = @company
    @comments = @commentable.comments.order('created_at desc').includes([:user, :events])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @addresses = @company.addresses
    @countries = @current_site.countries.all.map{ |c| [c.name, c.id] }
    # TODO lz states should have a country_id for auto-select
    @states = State.joins(:country).where(countries: {site_id: @current_site.id}).all.map{ |s| [s.name, s.id] }
    2.times { @company.addresses.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @addresses = @company.addresses.limit(2)
    @show_label = true

    @addresses.each do |add|
      if add.address_type?
        @states_1 = State.where(country_id: add.country_id).map{ |c| [c.name, c.id] }
      else
        @states_0 = State.where(country_id: add.country_id).map{ |c| [c.name, c.id] }
      end
    end

     @countries = Country.all.map{ |c| [c.name, c.id] }
  end

  # POST /companies
  # POST /companies.json
  def create
    @company.user_id = current_user.id
    @company.site = @current_site

    respond_to do |format|
      if @company.save
        track_activity @company
        format.html { redirect_to @company, notice: "#{t(:"messages.created")}" }
        format.json { render json: @company, status: :created, location: @company }
      else
        logger.error(@company.errors.full_messages.join"\n")

        format.html {
          @addresses = @company.addresses
          @states = State.joins(:country).where(countries: {site_id: @current_site.id}).all.map{ |s| [s.name, s.id] }
          render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update_attributes(params[:company])
        expire_fragment "#{t(:"activity.index.activities")}"
        expire_fragment "company_#{@company.id}_#{t(:"company.show.company")}_user"
        # todo
        # if @company.changed?
          track_activity @company
          @message = "#{t(:"messages.updated")}"
        # else
          # @message = "Nothing to update"
        # end
        format.html { redirect_to @company, notice: @message }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_contacts
    respond_to do |format|
      # format.html { redirect_to @company }
      format.js
    end
  end

  def show_address
    @addresses = @company.addresses
  end

  def show_comments
    @commentable = @company
    @comments = @commentable.comments.order('created_at desc')
    @comment = Comment.new
  end

  def sales
    @saleable = @company
    @sale = Sale.new
    @sales = @saleable.sales.order('created_at desc')
    @total = @sales.sum(&:ammount)
  end

  def revisions
    @versions = @company.versions.order("created_at desc")
  end

  def delete_company
    if @company.marked_to_remove == false
      @company.update_attributes(marked_to_remove: true)
    else
      @company.update_attributes(marked_to_remove: false)
    end
    redirect_to :back
  end
  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  def country_select_legal
    if params[:country_id].present?
      @states_0 = @current_site.countries.find(params[:country_id]).states
    else
      @states_0 = []
    end
    respond_to do |format|
      format.js
    end
  end

  def country_select_invoicing
    if params[:country_id].present?
      @states_1 = @current_site.countries.find(params[:country_id]).states
    else
      @states_1 = []
    end
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper

  def responsible_name(user)
    link_to user.full_name, profile_path(user)
  end

  def responsible_name_in_datatables(user)
    link_to user.full_name, url_helpers.profile_path(user)
  end

  def company_source(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end

    f.collection_select :company_source_id, current_site.company_sources, :id, lang,
                        { :prompt => t(:'company.form.source') }, class: 'select required'
  end

  def client_category(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end

    f.collection_select :client_category_id, current_site.client_categories, :id, lang,
                        { :prompt => t(:'company.form.client_category') }, class: 'select required'
  end

  def organizational_form(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end
    f.collection_select :organizational_form_id, current_site.organizational_forms, :id, lang,
                        { :prompt => t(:"company.form.organizational_form") }
  end

  def client_status(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end
    f.collection_select :client_status_id, current_site.client_statuses, :id, lang,
                        { :prompt => t(:'company.form.client_status') }, class: 'select required'
  end

  def client_type(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end
    f.collection_select :client_type_id, current_site.client_types, :id, lang,
                        { :prompt => t(:'company.form.client_type') }, class: 'select required'
  end

  def company_branch(f)
    if current_language == 'ro'
      lang = :name_ro
    elsif current_language == 'ru'
      lang = :name_ru
    else
      lang = :name
    end
    f.collection_select :company_branch_id, current_site.company_branches, :id, lang,
                        { :prompt => t(:'company.form.branch') }, class: 'select required'
  end

  def dt_client_type(company)
    if current_language == 'ro'
      company.client_type.name_ro
    elsif current_language == 'ru'
      company.client_type.name_ru
    else
      company.client_type.name
    end
  end

  def dt_client_category(company)
    if current_language == 'ro'
      company.client_category.name_ro
    elsif current_language == 'ru'
      company.client_category.name_ru
    else
      company.client_category.name
    end
  end

  def dt_company_source(company)
    if current_language == 'ro'
      company.company_source.name_ro
    elsif current_language == 'ru'
      company.company_source.name_ru
    else
      company.company_source.name
    end
  end

  def dt_company_branch(company)
    if current_language == 'ro'
      company.company_branch.name_ro
    elsif current_language == 'ru'
      company.company_branch.name_ru
    else
      company.company_branch.name
    end
  end

  def dt_organizational_form(company)
    if current_language == 'ro'
      company.organizational_form.name_ro
    elsif current_language == 'ru'
      company.organizational_form.name_ru
    else
      company.organizational_form.name
    end
  end

  def company_changes(version)
    version = version.changeset
  end

  def name_it(f, key)
    # TODO filter by site
    if f == 'company_branch_id'
      result = CompanyBranch.find key
      result_name(result)
    elsif f == 'company_source_id'
      result = CompanySource.find key
      result_name(result)
    elsif f == 'client_category_id'
      result = ClientCategory.find key
      result_name(result)
    elsif f == 'client_type_id'
      result = ClientType.find key
      result_name(result)
    elsif f == 'client_status_id'
      result = ClientStatus.find key
      result_name(result)
    elsif f == 'responsible_id'
      result = User.find key
      return result.full_name
    elsif f == 'organizational_form_id'
      result = OrganizationalForm.find key
      result_name(result)
    elsif f == 'marked_to_remove'
      marked_to_remove(key)
    elsif f == 'updated_at'
      return l key, format: :long
    elsif f == 'client_type_id'
      result = ClientType.find key
      result_name(result)
    else f == 'client_at'
      return key
    end
  end

  def result_name(result)
    if current_language == 'en'
      return result.name
    elsif current_language == 'ro'
      return result.name_ro
    else
      return result.name_ru
    end
  end

  def marked_to_remove(key)
    t(key ? :to_delete : :to_not_delete)
  end

  def show_country(address)
    if current_language == 'ro'
      address.country.name_ro
    elsif current_language == 'ru'
      address.country.name_ru
    else
      address.country.name
    end
  end

  def show_state(address)
    if current_language == 'ro'
      address.state.name_ro
    elsif current_language == 'ru'
      address.state.name_ru
    else
      address.state.name
    end
  end
end

app/views/companies/_contacts.html.erb
<h4><%= t(:"contacts.show.contacts")  %></h4>
<% for employee in @company.employee %>
  <div class="span4 pull-right">
    <%= link_to employee.full_name, company_employee_path(@company, employee) %>
    <%= link_to "<i class='icon-edit'></i>".html_safe, edit_company_employee_path(@company, employee) %>
    <br>
    <%= employee.phone %><br>
    <%= employee.decision? ? t(:"contacts.show.take") : t(:"contacts.show.cant_take") %><br>
    <hr>
  </div>
<% end %>

app/views/companies/_field_filter.html.erb
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <%= t(:"company.index.filter") %>
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="well well-small">
          <ul class="filter">
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(0);" checked><%= t(:"company.index.id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(1);" checked><%= t(:"company.index.created_at") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(2);" checked><%= t(:"company.index.name") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(3);" checked><%= t(:"company.index.client_category_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(4);" checked><%= t(:"company.index.client_type_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(5);" checked><%= t(:"company.index.company_source_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(6);" checked><%= t(:"company.index.company_branch_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(7);" checked><%= t(:"company.index.phone") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(8);" checked><%= t(:"company.index.fax") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(9);" checked><%= t(:"company.index.skype") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(10);" checked><%= t(:"company.index.email") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(11);" checked><%= t(:"company.index.fisc_id") %></li>
            <li><input type="checkbox" name="vehicle" value="" onclick="fnShowHide(12);" checked><%= t(:"company.index.responsible_id") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/_history.html.erb
<h4><%= t(:'changes_history') %></h4>
<div class="accordion" id="accordion2">
  <% @versions.each_with_index do |version, index| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <div class="index pull-left"><%= index + 1 %></div>
      <div class="version_date">
      <%= link_to "#collapse#{index+1}", class: "accordion-toggle", data: {toggle: "collapse", parent: "#accordion2"} do %>
        <%= User.find(version.whodunnit).full_name %> <%= t(:'changed_at') %> <%= l version.created_at, format: :long %>
      <% end %>
      </div>
    </div>
    <div id="collapse<%= index+1 %>" class="accordion-body collapse">
      <div class="accordion-inner">
        <div>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th></th>
                <th><%= t(:"company.history.from") %></th>
                <th><%= t(:"company.history.to") %></th>
              </tr>
            </thead>
            <tbody>
              <% version.changeset.each do |set| %>
                <tr>
                  <td><%= t(:"company.index.#{set[0]}") %></td>
                  <td><%= name_it(set[0], set[1][0]) %></td>
                  <td><%= name_it(set[0], set[1][1]) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to t(:"history.restore"), revert_version_path(version), :method => :post %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/companies/_marked_to_delete.html.erb
<div class="alert alert-error">
  <%= t(:"marked_to_delete") %>
</div>
<% if can? :manage, @all %>
<%= link_to t(:"helpers.links.cancel"), delete_company_company_path(@company), :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
<% end %>

app/views/companies/_profile_for_user.html.erb
<dt><strong><%= t(:"company.show.added_by") %>:</strong></dt>
<dd><%= link_to @company.user.full_name, profile_path(@company.user) if @company.user.present? %></dd>
<dt><strong><%= t(:"company.show.responsible") %>:</strong></dt>
<dd><%= responsible_name(@company.resp_user) %></dd>
<dt><strong><%= t(:"company.show.number_employees") %>:</strong></dt>
<dd><%= @company.number_employees %></dd>
<dt><strong><%= t(:"company.show.organizational_form") %>:</strong></dt>
<dd><%= dt_organizational_form(@company) if @company.organizational_form.present? %></dd>
<dt><strong><%= t(:"company.show.company_branch") %>:</strong></dt>
<dd><%= dt_company_branch(@company) %></dd>
<dt><strong><%= t(:"company.show.company_source") %>:</strong></dt>
<dd><%= dt_company_source(@company) %></dd>
<dt><strong><%= t(:"company.show.client_category") %>:</strong></dt>
<dd><%= dt_client_category(@company) %></dd>
<dt><strong><%= t(:"company.show.client_type") %>:</strong></dt>
<dd><%= dt_client_type(@company) %></dd>
<dt><strong><%= t(:"company.show.client_at") %>:</strong></dt>
<dd><%= l(@company.client_at, format: :long) if @company.client_at.present? %></dd>
<dt><strong><%= t(:"company.show.phone") %>:</strong></dt>
<dd><%= @company.phone %></dd>
<dt><strong><%= t(:"company.show.fax") %>:</strong></dt>
<dd><%= @company.fax %></dd>
<dt><strong><%= t(:"company.show.email") %>:</strong></dt>
<dd><%= @company.email %></dd>
<dt><strong><%= t(:"company.show.skype") %>:</strong></dt>
<dd><%= @company.skype %></dd>
<dt><strong><%= t(:"company.show.website") %>:</strong></dt>
<dd><%= @company.website %></dd>
<dt><strong><%= t(:"company.show.facebook") %>:</strong></dt>
<dd><%= @company.facebook %></dd>
<dt><strong><%= t(:"company.show.bank_req") %>:</strong></dt>
<dd><%= @company.bank_req %></dd>
<dt><strong><%= t(:"company.show.fisc_id") %>:</strong></dt>
<dd><%= @company.fisc_id %></dd>

app/views/companies/_sales.html.erb
<script type="text/javascript">
(function() {
  jQuery(function() {
    return Morris.Line({
      element: 'sales_chart',
      data: $('#sales_chart').data('sales'),
      xkey: 'sale_date',
      ykeys: ['ammount'],
      labels: ['<%= t(:"sales.index.amount") %>']
    });
  });

}).call(this);
</script>
<%= content_tag :div, "", id: "sales_chart", data: {sales: company_sales_chart_data} %>

<h4><%= t(:"sales.show.sales") %></h4>
<div class="img-polaroid"><%= render partial: 'sales/form' %></div>
<div class="page-header">
  <h4>
    <%= t(:"sales.show.sales") %> <span class="total_sales"><%= @sales.count %></span>
    <span class="pull-right"><%= t(:"sales.show.total_amount") %>: <span class="total_ammount"><%= @total %></span>
    <%= t(:"sales.index.lei") %></span>
  </h4>
</div>
<div class="comments">
  <%= render @sales %>
</div>

app/views/companies/country_select_invoicing.js.erb
<% if current_language == "ru" %>
  $('.control-group .controls.state_1').html('<%= j select_tag :state_id, options_for_select(@states_1.map{|s| [s.name_ru, s.id]}),
    name: "company[addresses_attributes][1][state_id]", id: "state_id_1" if @states_1.count > 0 %>');
  <% elsif current_language == "ro" %>
    $('.control-group .controls.state_1').html('<%= j select_tag :state_id, options_for_select(@states_1.map{|s| [s.name_ro, s.id]}),
      name: "company[addresses_attributes][1][state_id]", id: "state_id_1" if @states_1.count > 0 %>');
  <% else %>
    $('.control-group .controls.state_1').html('<%= j select_tag :state_id, options_for_select(@states_1.map{|s| [s.name, s.id]}),
      name: "company[addresses_attributes][1][state_id]", id: "state_id_1" if @states_1.count > 0 %>');
<% end %>

app/views/companies/index.html.erb
<%#= render "advanced_search" %>
<div class="page-header">
  <h2><%= t(:"company.index.companies") %></h2>
  <%= link_to t('company.form.new_company', :default => t("helpers.links.new")), new_company_path %>
</div>
<%= render 'field_filter' %>
<hr>
<table id="companies" class="display" data-source="<%= companies_url(format: "json") %>" data-language="<%= current_language %>">
  <thead>
    <tr>
      <th><%= t(:"company.index.id") %></th>
      <th><%= t(:"company.index.created_at") %></th>
      <th><%= t(:"company.index.name") %></th>
      <th><%= t(:"company.index.client_category_id") %></th>
      <th><%= t(:"company.index.client_type_id") %></th>
      <th><%= t(:"company.index.company_source_id") %></th>
      <th><%= t(:"company.index.company_branch_id") %></th>
      <!-- <th><%#= t(:"company.index.client_at") %></th> -->
      <th><%= t(:"company.index.phone") %></th>
      <th><%= t(:"company.index.fax") %></th>
      <th><%= t(:"company.index.skype") %></th>
      <th><%= t(:"company.index.email") %></th>
      <th><%= t(:"company.index.fisc_id") %></th>
      <th><%= t(:"company.index.responsible_id") %></th>
      <!-- <th><%#=t '.actions', :default => t("helpers.actions") %></th> -->
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/companies/search.html.erb
<%= render "advanced_search" %>

<div class="page-header">
  <h1><%= t(:"company.index.companies") %></h1>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_company_path %>
</div>
<table id="search_companies" class="table table-striped" data-language="<%= current_language %>">
  <thead>
    <tr>
      <th><%= t(:"company.index.id") %></th>
      <!-- <th><%#= t(:"company.index.created_at") %></th> -->
      <th><%= t(:"company.index.name") %></th>
      <!-- <th><%#= t(:"company.index.client_category_id") %></th> -->
      <!-- <th><%#= t(:"company.index.client_type_id") %></th> -->
      <!-- <th><%#= t(:"company.index.company_source_id") %></th> -->
      <!-- <th><%#= t(:"company.index.client_at") %></th> -->
      <th><%= t(:"company.index.phone") %></th>
      <th><%= t(:"company.index.fax") %></th>
      <th><%= t(:"company.index.email") %></th>
      <!-- <th><%#= t(:"company.index.responsible_id") %></th> -->
      <!-- <th><%#=t '.actions', :default => t("helpers.actions") %></th> -->
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td><%= company.id %></td>
      <td><%= link_to(company.name, company) %></td>
      <td><%= company.phone %></td>
      <td><%= company.fax %></td>
      <td><%= company.email %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="row-fluid">
  <div class="">
    <h1><%= best_in_place @company, :name %></h1>
  </div>

<div class="row-fluid">
  <div class="form-actions">
    <% if can? :update, @company %>
      <%= link_to t(:"company.show.edit"), edit_company_path(@company), :class => 'btn' %>
      <%= link_to t(:"company.show.destroy"), delete_company_company_path(@company), :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' unless @company.to_delete? %>
    <% end %>
    <%= link_to t(:"company.show.add_contact"), new_company_employee_path(@company), :class => 'btn'  %>
    <span class="marked_to_delete pull-right">
      <% if @company.to_delete? %>
        <%= render 'marked_to_delete' %>
      <% end %>
    </span>
  </div>
</div>

  <div class="span4" style=<%= @company.to_delete? ? "background:#f2dede;" : "" %>>
    <h4><%= t(:"company.show.company_profile") %></h4>
    <dl class="dl-horizontal">
      <% if @company.user == current_user %>
        <%= render 'profile_for_owner' %>
      <% else %>
        <% cache "company_#{@company.id}_#{t(:"company.show.company")}_user" do %>
          <%= render 'profile_for_user' %>
        <% end %>
      <% end %>
    </dl>
  </div>
  <div class="span6">
    <ul class="nav nav-tabs">
      <li class="address_tab"><%= link_to t(:"company.show.address"), show_address_company_path, remote: true %></li>
      <li class="contacts_tab">
        <%= link_to show_contacts_company_path, remote: true do %>
        <%= t(:"company.show.contacts") %> <span class="badge badge-inverse total_employee"><%= @company.employee.count %></span>
        <% end %>
      </li>
      <li class="comments_tab active">
        <%= link_to show_comments_company_path, remote: true, class: 'tab_comments' do %>
        <%= t(:"company.show.comments") %> <span class="badge badge-inverse total_comments"><%= @company.comments.count %></span>
        <% end %>
      </li>
      <li class="sales_tab">
        <%= link_to sales_company_path, remote: true do %>
        <%= t(:"company.show.sales") %> <span class="badge badge-inverse total_sales"><%= @company.sales.count %></span>
        <% end %>
      </li>
      <% if can? :manage, Version %>
      <li class="history_tab">
        <%= link_to revisions_company_path, remote: true do %>
        <%= t(:'changes_history') %> <span class="badge badge-inverse total_versions"><%= @company.versions.count %></span>
        <% end %>
      </li>
      <% end %>
    </ul>
    <div class="right_side">
      <% cache "company_#{@company.id}_#{t(:"company.show.comments")}" do %>
        <%= render 'comments' %>
      <% end %>
    </div>
  </div>
</div>

<%#= link_to t(:"company.show.destroy"), company_path(@company), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' %>